spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/product_service_db
    redis:
      host: localhost

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  otlp:
    tracing:
      endpoint: http://localhost:4318/v1/traces
